# Generated by Django 3.0.8 on 2020-07-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_num', models.IntegerField()),
                ('board_num', models.IntegerField()),
                ('post_name', models.CharField(max_length=100)),
                ('post_detail', models.CharField(max_length=300)),
                ('post_link', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=100)),
                ('post_views', models.IntegerField()),
            ],
        ),
    ]
