# Generated by Django 3.0.8 on 2020-07-31 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myinfo', '0002_auto_20200731_1422'),
        ('Board', '0003_auto_20200731_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myinfo.Myinfo'),
        ),
    ]
