# Generated by Django 3.0.8 on 2020-07-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0004_auto_20200731_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_num',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
