# Generated by Django 3.0.8 on 2020-07-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0005_auto_20200731_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_views',
            field=models.IntegerField(default=0),
        ),
    ]
