# Generated by Django 3.0.8 on 2020-07-31 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0006_auto_20200731_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_write',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
