# Generated by Django 3.0.8 on 2020-08-01 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0007_post_post_write'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='board_num',
            new_name='board_name',
        ),
    ]
