# Generated by Django 3.0.8 on 2020-08-01 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myinfo', '0007_auto_20200731_1519'),
        ('Sendemail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendemail',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myinfo.Myinfo'),
        ),
    ]
