# Generated by Django 3.0.8 on 2020-08-01 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sendemail', '0002_auto_20200801_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendemail',
            name='email',
        ),
    ]
