# Generated by Django 3.0.8 on 2020-08-01 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sendemail', '0003_remove_sendemail_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendemail',
            name='email',
            field=models.CharField(default='jje0ng@kookmin.ac.kr', max_length=30),
        ),
    ]
