# Generated by Django 3.0.8 on 2020-07-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('github_link', models.CharField(max_length=100)),
                ('skill', models.CharField(max_length=500)),
                ('sns', models.CharField(max_length=100)),
                ('introduction', models.CharField(max_length=1000)),
            ],
        ),
    ]
