# Generated by Django 3.0.8 on 2020-08-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polioapp', '0003_auto_20200820_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nblog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_boardnum', models.IntegerField(default=2)),
                ('n_title', models.CharField(max_length=200)),
                ('n_pub_date', models.DateTimeField(verbose_name='date published')),
                ('n_body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pblog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_boardnum', models.IntegerField(default=1)),
                ('p_title', models.CharField(max_length=200)),
                ('p_pub_date', models.DateTimeField(verbose_name='date published')),
                ('p_body', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
