# Generated by Django 3.0.8 on 2020-08-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polioapp', '0004_auto_20200820_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nblog',
            name='n_boardnum',
        ),
        migrations.RemoveField(
            model_name='pblog',
            name='p_boardnum',
        ),
        migrations.AddField(
            model_name='nblog',
            name='p_boardname',
            field=models.CharField(default='News', max_length=200),
        ),
        migrations.AddField(
            model_name='pblog',
            name='p_boardname',
            field=models.CharField(default='Project', max_length=200),
        ),
    ]
